### ISSUE TITLE
path for errors

### ISSUE THREAD

**Issue by voxspox** [schematics/schematics#242]
Hi,

I want to use schematics for web forms validation. In my model I have a list of integers, thus I defined:
```python
    class Form(Model):
        mapping = ListType(IntType)
```
after loading the model with some (invalid) form data p.ex. `{ 'mapping' : [ u'1', u'2', u'' ] }` I get a `ModelConversionError: { 'mapping': [u'Value is not int']}`

It is correct that there is an error, but I want to show to the user which field is wrong. Thus something like { 'mapping.2': [u'Value is not int']}` would be nice.

knut

**Comment by apranav19** [comment]
Hi,
I can try working on this. Thanks!

**Comment by apranav19** [comment]
Fixed this issue.
The new error message contains the invalid value. 
For example:

**Comment by voxspox** [comment]
Thanks for your improvement. I want to remark that with this change it is still not possible to find the faulty field. This is important to show a error message besides the faulty form field.

**Comment by apranav19** [comment]
Hi,
Just to confirm, you would like to see the index/field that is faulty within a `CompoundType`?

**Comment by voxspox** [comment]
Hi, I didn't found ```CompoundType``` in the docs, but I think yes. Just imagine you have a web form. All fields are declared in a ```Model```. An error in a field should be presented next to the field. Thus I need some precise info for which field the error is.

In my example given there is a field mapping which is a list of integers. The error message says that there is an error in mapping, but it does not say which field of mapping is faulty.

**Comment by bintoro** [comment]
This issue seems identical to that reported as #307. There's a pending PR #331 that provides a patch. Please reopen if the proposed solution does not solve the problem.
